-- AlterTable
ALTER TABLE `Contato` MODIFY `situacao` CHAR(1) NULL DEFAULT '1';

-- AlterTable
ALTER TABLE `empresas` MODIFY `situacao` CHAR(1) NULL DEFAULT '1',
    MODIFY `dhCriacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `dhAtualizacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `enderecos` MODIFY `dhCriacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `dhAtualizacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `situacao` CHAR(1) NULL DEFAULT '1';

-- AlterTable
ALTER TABLE `usuarios` MODIFY `situacao` CHAR(1) NULL DEFAULT '1',
    MODIFY `dhCriacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `dhAtualizacao` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
